fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
      address: "mail@mail.com"
      sender_name: "Sender Name"
  registration:
      form:
          type: App\Form\RegistrationFormType